### PR TITLE
Added option to pass auth ID into __contructor function.

### PR DESCRIPTION
**Pull request by riogezz**
This lets users that are already logged in into web interface, to use auth id from cookies (zbx_sessionid) with the API, instead of logging in again.
e.g.:
     $zbx_sessionid=$_COOKIE['zbx_sessionid'];
     $api = new ZabbixApi('http://192.168.119.130/zabbix/api_jsonrpc.php','','','','',$zbx_sessionid);

### CODE REVIEW

**Comment by domibarton** [comment]
Hi

Thanks for your contribution.
Great feature, indeed :)

But there's some design flaws. It works pretty well if you're using it without a HTTP basic auth. Though if you're using basic auth and a session ID, it doesn't work, because the basic auth credentials won't be set.

I'll create a new branch for your master, fix & rebase it, and finally merge it back to the my master branch. Thanks a lot for your work and idea!

Cheers
Domi

**Comment by domibarton** [comment]
I've built the new libraries in the branches [2.2](https://github.com/confirm-it-solutions/PhpZabbixApi/tree/2.2) and [2.4](https://github.com/confirm-it-solutions/PhpZabbixApi/tree/2.4).

@riogezz can you test them for me and give me a feedback?

**Comment by riogezz** [comment]
sorry, didn't see your message and did the same correction you already did in bugfix. Discard this pull request, please.
It's working really well. 
Thank you for your work.

**Comment by domibarton** [comment]
you're welcome.
thanks for your contribution @riogezz

**Pull request closed without merging**
